"""
Main pipeline orchestrator (Zero-Download Streaming Variant).
Coordinates: stream extraction → direct transcription → chunk → map → reduce → flashcards
"""

import os
import logging
from datetime import datetime

from models.job import get_job, JobStatus
from services.audio import download_youtube, extract_audio
from services.transcription import transcribe_audio
from services.llm import (
    clean_transcript,
    map_chunk,
    reduce_to_notes,
    generate_summary,
    generate_flashcards,
)
from utils.chunker import chunk_transcript

logger = logging.getLogger(__name__)


async def run_pipeline(job_id: str):
    print(f"\n{'=' * 60}")
    print(f"🚀 PIPELINE STARTED: {job_id}")
    print(f"{'=' * 60}\n")

    job = get_job(job_id)

    if not job:
        logger.error(f"Job {job_id} not found")
        return

    try:
        # STEP 1 — EXTRACT REMOTE YOUTUBE AUDIO STREAM
        if job.source_type == "url":
            print("📥 STEP 1 — EXTRACTING REMOTE YOUTUBE STREAM LINK")
            job.update_status(JobStatus.DOWNLOADING)

            # Now returns a high-speed direct stream URL hosted on Google servers
            audio_stream_url = await download_youtube(job.source_url, job_id)

            job.audio_path = audio_stream_url
            job.source_path = audio_stream_url

            print("✅ STREAM LINK EXTRACTION COMPLETE")

        # STEP 2 — EXTRACT AUDIO FROM LOCAL FILE UPLOAD
        if job.source_type == "file":
            print("🎵 STEP 2 — EXTRACTING AUDIO FROM UPLOADED VIDEO")
            job.update_status(JobStatus.EXTRACTING_AUDIO)

            audio_path = await extract_audio(job.source_path, job_id)
            job.audio_path = audio_path

            print("✅ AUDIO EXTRACTION COMPLETE")

        # STEP 3 — TRANSCRIBE (Whisper reads file OR streams network URL directly)
        print("📝 STEP 3 — TRANSCRIBING")
        job.update_status(JobStatus.TRANSCRIBING)

        raw_transcript = await transcribe_audio(job.audio_path)

        if not raw_transcript.strip():
            raise ValueError("Empty transcription generated by model.")

        print("✅ TRANSCRIPTION COMPLETE")

        # STEP 4 — CLEAN TRANSCRIPT
        print("🧹 STEP 4 — CLEANING TRANSCRIPT")
        job.update_status(JobStatus.CHUNKING)

        cleaned_transcript = await clean_transcript(raw_transcript)
        job.transcript = cleaned_transcript

        print("✅ CLEANING COMPLETE")

        # STEP 5 — CHUNKING
        print("✂️ STEP 5 — CHUNKING")
        chunks = chunk_transcript(
            cleaned_transcript,
            words_per_chunk=300,
        )

        if not chunks:
            raise ValueError("No text chunks generated")

        print(f"✅ CREATED {len(chunks)} CHUNKS")

        # STEP 6 — MAP PHASE
        print("🧠 STEP 6 — MAP PHASE")
        job.update_status(JobStatus.MAP_PROCESSING)
        analyses = []

        for i, chunk in enumerate(chunks):
            print(f"🔹 CHUNK {i+1}/{len(chunks)}")
            extra = int((i / len(chunks)) * 14)
            job.progress = 65 + extra

            analysis = await map_chunk(chunk, i, len(chunks))
            analyses.append(analysis)

        print("✅ MAP PHASE COMPLETE")

        # STEP 7 — REDUCE PHASE
        print("📚 STEP 7 — REDUCE PHASE")
        job.update_status(JobStatus.REDUCE_PROCESSING)

        notes = await reduce_to_notes(analyses)
        job.notes = notes

        print("✅ NOTES GENERATED")

        # STEP 8 — SUMMARY
        print("📄 STEP 8 — SUMMARY")
        job.progress = 85

        summary = await generate_summary(notes)
        job.summary = summary

        print("✅ SUMMARY GENERATED")

        # STEP 9 — FLASHCARDS
        print("🃏 STEP 9 — FLASHCARDS")
        job.update_status(JobStatus.GENERATING_FLASHCARDS)

        flashcards = await generate_flashcards(notes)
        job.flashcards = flashcards

        print("✅ FLASHCARDS GENERATED")

        # FINALIZE
        print("🎉 FINALIZING")
        job.update_status(JobStatus.COMPLETED)
        job.completed_at = datetime.utcnow().isoformat()

        print("✅ JOB COMPLETED SUCCESSFULLY")
        _cleanup_files(job)

    except Exception as e:
        logger.error(f"[{job_id}] Pipeline execution failed: {e}", exc_info=True)
        print("❌ PIPELINE FAILED")
        print("ERROR:", str(e))
        
        job.status = JobStatus.FAILED
        job.error = str(e)
        job.label = f"Failed: {str(e)[:100]}"


def _cleanup_files(job):
    """Clean up uploaded source files and extracted audio files from local disk storage."""
    files_to_remove = []

    # Clean up local file uploads only (Bypass removing strings starting with HTTP network tracks)
    if job.source_type == "file":
        if job.source_path and os.path.exists(job.source_path):
            files_to_remove.append(job.source_path)
        if job.audio_path and job.audio_path != job.source_path and os.path.exists(job.audio_path):
            files_to_remove.append(job.audio_path)

    for f in files_to_remove:
        try:
            if f and os.path.exists(f):
                os.remove(f)
                print(f"🗑️ Cleaned up storage: {f}")
        except Exception as e:
            print(f"⚠️ Disk cleanup optimization failed: {e}")